In [1]:
# Decision Tree 
import numpy as np


In [36]:
x = np.array([1,3,4,5,6,7,5])
y = np.array([0,0,0,0,0,0,0])

In [27]:
np.mean((x-np.mean(x))**2)

3.387755102040817

In [28]:
np.bincount(x)/sum(np.bincount(x))

array([ 0.        ,  0.14285714,  0.        ,  0.14285714,  0.14285714,
        0.28571429,  0.14285714,  0.14285714])

In [25]:
-sum([p* np.log2(p) for p in np.bincount(x)/np.sum(np.bincount(x)) if p > 0 ])

2.5216406363433181

In [31]:
1-sum([(i/np.sum(np.bincount(x)))**2 for i in np.bincount(x)])

0.81632653061224492

In [39]:
np.zeros(3)[y[0]]=1

In [62]:
prob=np.zeros(3)

In [63]:
prob[y[0]]=1.0

In [64]:
prob

array([ 0.,  1.,  0.])

In [66]:
y[0]

1

In [171]:
y=np.array([1,1,1,1,1,1,1])

In [178]:
y = np.array([[1,2,3],[2,3,4]])
np.mean(y,axis=1)

array([ 2.,  3.])

In [60]:
np.bincount(y,minlength=2)/len(y)

array([ 0.42857143,  0.57142857])

In [33]:
X = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,3],[3,2,5,6]])

In [37]:
X[:,1]>3

array([False, False,  True, False], dtype=bool)

In [34]:
N,M = X.shape

In [35]:
X.shape

(4, 4)

In [94]:
np.random.choice(M,2,replace=False)

array([2, 1])

In [109]:
Y = np.array([1,0,1,1])

In [111]:
for i in np.random.choice(M,2,replace=False):
    print(i)

3
1


In [38]:
levels=np.unique(X[:,3])

In [40]:
X[:,3]

array([4, 5, 3, 6])

In [39]:
levels

array([3, 4, 5, 6])

In [27]:
vals=X[:,3]

IndexError: too many indices for array

In [130]:
levels

array([3, 4, 5, 6])

In [131]:
vals

array([4, 5, 3, 6])

In [118]:
(levels[:-1]+levels[1:])/2

array([ 3.5,  4.5,  5.5])

In [116]:
levels[1:]

array([4, 5, 6])

In [121]:
Y

array([1, 0, 1, 1])

In [128]:
-sum([p*np.log2(p) for p in np.bincount(Y)/len(Y) if p>0])

0.81127812445913283

In [30]:
left=np.argwhere(vals<=3.5).flatten()

In [31]:
right=np.argwhere(vals>3.5).flatten()

In [32]:
left

array([2])

In [29]:
vals=np.array([4, 5, 3, 6])

In [137]:
n = len(Y)

In [142]:
-sum([p*np.log2(p) for p in np.bincount(Y[right])/len(right) if p>0])

0.91829583405448956

In [141]:
Y[left]

array([1])

In [143]:
n_l,n_r = 1,3
e_l,e_r = -0.0,0.91829

In [144]:
n_l/n *e_l

-0.0

In [145]:
?ininstance

Object `ininstance` not found.


In [11]:
seed = 3

if seed:
    n=np.random.seed(seed)
    print(n)
    print(np.random.seed(seed))

None
None


In [4]:
v_seed

NameError: name 'v_seed' is not defined

In [12]:
# 使用Numpy重写 Decision Tree

import numpy as np

In [25]:
X = np.array([1,2,3,4,5,6])
Y = np.array([0,1,0,0,1,0])

In [18]:
#先从简单的代码进行处理，例如定义函数的评估函数
def mse(y):
    return np.mean((y - np.mean(y))**2)

def entropy(y):
    hist = np.bincount(y)
    ps = hist /np.sum(hist)
    return  -np.sum([p*np.log2(p) for p in ps if p > 0])
def gini(y):
    hist = np.bincount(y)
    ps = hist/np.sum(hist)
    return 1- np.sum([i**2 for i in ps])

In [19]:
print(mse(Y))
print(entropy(Y))
print(gini(Y))

0.222222222222
0.918295834054
0.444444444444


In [21]:
print(mse(Y))
print(entropy(Y))
print(gini(Y))

0.222222222222
0.918295834054
0.444444444444


In [122]:
def mse(y):
    """
    Mean squared error for decision tree (ie., mean) predictions
    """
    return np.mean((y - np.mean(y)) ** 2)


def entropy(y):
    """
    Entropy of a label sequence
    """
    hist = np.bincount(y)
    ps = hist / np.sum(hist)
    return -np.sum([p * np.log2(p) for p in ps if p > 0])


def gini(y):
    """
    Gini impurity (local entropy) of a label sequence
    """
    hist = np.bincount(y)
    N = np.sum(hist)
    return 1 - sum([(i / N) ** 2 for i in hist])


In [22]:
# 和学习看的模仿资料一样，主要难点是在于分裂上，这点对于没有怎么写类的我来说还是比较困难
# 目前的策略就是先模仿写这再去改进
# 需要克服的难点是转变思维 不再是过程上的变成而是面向对象的变编程，不过就理解为模版 属性方法之类的东西吧

In [47]:
?np.random.choice()

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

        .. versionadded:: 1.7.0

Parameters
-----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if a was np.arange(n)
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given the sample assumes a uniform distribution over all
    entries in a.

Returns
--------
samples : 1-D ndarray, shape (size,)
    The generated random samples

Raises
-------
ValueError
    If a is an int and less than zero, if a or p are not 1-dimensional,
    if a is an array-like of 

In [23]:
import numpy as np

In [127]:
class Node:
    def __init__(self,left,right,rule):
        self.left = left
        self.right = right
        self.feature = rule[0]
        self.threshold = rule[1]

class Leaf:
    def __init__(self,value):
        self.value = value
        
#定义好了节点和叶子之后开始进行决策树类的编写，涉及到许多方法，这段对于我而言其实有点搞
#对于决策数类的定义这块，可以考虑流程化的角度去看，刚才定义的节点和叶子的时候，其实有点像那种最小化知识的思考
#对于刚开始的决策树设计流程而言的话，就假设我是开始弄决策树了，我刚开始的深度肯定为0，根节点还没有。为了开始进行树的生长，我需要选择选择选择的变量，
#按照什么标准进行分裂，最大深度是多少，计算叶子的时候，是按照目标是分类变量还是连续值，连续值的话可输出值，离散值的话输出概率，基本就是这思路，如果这样
#想的话其实整个程序的思路还是比较清楚的，说白了这个的初始化就是说
class DecisionTree:
    def __init__(self,classifier =True,max_depth=None,n_feats=None,criterion='entropy',seed=None,):
        if seed:
            np.random.seed(seed)
        
        self.depth = 0
        self.root = None
        
        self.n_feats = n_feats
        self.criterion = criterion
        self.classifier = classifier
        self.max_depth = max_depth if max_depth else np.inf
        
        if not classifier and criterion in ['gini','entropy']:
            raise ValueError(
                "{} is a valid criterion only when classifier = True.".format(criterion)
            )
        if classifier and criterion == 'mse':
            raise ValueError("'mse' is a valid criterion only when classifier = Flase.")
            
    def fit(self,X,Y):
        self.n_classes = max(Y) + 1 if self.classifier else None
        self.n_feats = X.shape[1] if not self.n_feats else min(self.n_feats,X.shape[1])
        self.root=self._grow(X,Y)
        
    def predict(self,X):
        return np.array([self._traverse(x,self.root) for x in X])
    
    def predict_class_probs(self,X):
        assert self.classifier,"'predict_calss_probs' undefined for classifier = False"
        return np.array([self._traverse(x,self.root,prob=True) for x in X])
#下面的函数才基本上是整个决策树的关键，涉及到了树的生长分割，计算信息增益等基本的计算，不过由于类的饮用稍微还是有点绕
#在写这个程序的时候发现作者有个习惯，就是喜欢将那些异常的特殊的情况进行讨论，然后再看正常的情况
#要看数据的生长那先看那些情况下我们不进行分割，一个是我分组比较完美，可以分的干净，另一个是达到我最大的学习深度了
    def _grow(self,X,Y):
        if len(set(Y))==1:
            if self.classifer:
                prob = np.zeros(self.n_classes)
                prob[Y[0]] = 1.0
            return Leaf(prob) if self.classifer else Leaf(Y[0])
        
        if self.depth >= self.max_depth:
            v = np.mean(Y,axis=0)
            if self.classifier:
                v = np.bincount(Y,minlength=self.n_classes) / len(Y)
            return Leaf(v)
#特殊的情况处理好了之后便开始进行树的生长        
        N,M = X.shape
        self.depth += 1
        feat_idxs = np.random.choice(M,self.n_feats,replace=True)
        
        feat,thresh = self._segment(X,Y,feat_idxs)
        l = np.argwhere(X[:,feat] <= thresh).flatten()
        r = np.argwhere(X[:,feat] > thresh).flatten()
        
#这个转换好不错，我还反应了下，个人觉得好不错,而且还是类的递归
        left = self._grow(X[l,:],Y[l])
        right = self._grow(X[r,:],Y[r])
        return Node(left,right,(feat,thresh))

    def _segment(self,X,Y,feat_idxs):
        best_gain = -np.inf
        split_idx,split_thresh = None,None
        for i in feat_idxs:
            vals = X[:,i]
            levels = np.unique(vals)
            thresholds = (levels[:-1]+levels[1:])/2 
            gains = np.array([self._impurity_gain(Y,t,vals) for t in thresholds])
#关于为什么要这样设置阈值，我都不知道为什么，不过也可以说出个大概来，就是对特征变量的值进行去重排序，取中间值进行阈值的筛选
            if gains.max() > best_gain:
                split_idx = i
                best_gain = gains.max()
                split_thresh = thresholds[gains.argmax()]
        return split_idx,split_thresh
#计算信息增益，分解下来就是简单的母节点的信息熵 - 叶节点的信息熵    
    def _impurity_gain(self,Y,split_thresh,feat_values):
        if self.criterion == "entropy":
            loss = entropy
        elif self.criterion == "gini":
            loss = gini
        elif self.criterion == "mse":
            loss = mse
        
        parent_loss = loss(Y)
        
        left = np.argwhere(feat_values <= split_thresh).flatten()
        right = np.argwhere(feat_values > split_thresh).flatten()
        
        if len(left) == 0 or len(right) == 0:
            return 0
#为啥返回0 呢？我也有点纳闷，增益为0？
        
        n = len(Y)
        n_l,n_r = len(left),len(right)
        e_l,e_r = loss(Y[left]),loss(Y[right])
        child_loss = (n_l/n) * e_l + (n_r/n)*e_r
        
        ig = parent_loss -child_loss
        
        return ig
# 这里的value是指的叶子节点？这个递归也也太多了吧
    def _traverse(self,X,node,prob = False):
        if isinstance(node,Leaf):
            if self.classifier:
                return node.value if prob else node.value.argmax()
            return node.value
        if X[node.feature] <= node.threshold:
            return self._traverse(X,node.left,prob)
        return self._traverse(X,node.right,prob)
# 这个traversek看的我比较迷，表示需要这个吗
    

    
        #先从简单的代码进行处理，例如定义函数的评估函数
    def mse(y):
        return np.mean((y - np.mean(y))**2)

    def entropy(y):
        hist = np.bincount(y)
        ps = hist /np.sum(hist)
        return  -np.sum([p*np.log2(p) for p in ps if p > 0])
    def gini(y):
        hist = np.bincount(y)
        ps = hist/np.sum(hist)
        return 1- np.sum([i**2 for i in ps])

In [45]:
# 至此就把简单的决策树给看完了，其实说实在知道理论和实际操作完全是两件事情，有些时候对于数据的处理都没有想好该怎么做，还有递归思想，解决了关于不断分裂的
# 问题，这点对于我而言其实还是有借鉴意义，之前高清圆还跟我讨论过这个问题，今天收获了之后还是很用的

In [63]:
# 这个基本上就是整个决策树的最根基的东西，所以这个代码最好自己要好好看，其实对于生活中的决策这个也是极其有实验意义的 因为这个算法足够的简单
# 20191121号去听那个孤独大脑 老喻的讲座无不体现着这个决策树 坦白而言 我并没有觉得老喻将的有多好 他说的那些我都知道 但是我缺的是将这些内容系统化的整理起来
# 这才是我的问题，或者说我应该努力去解决的

In [64]:
# 随机森林的编写，用到了决策树

import numpy as np
from .dt import DecisionTree


ModuleNotFoundError: No module named '__main__.dt'; '__main__' is not a package

In [120]:
# 使用自主法进行有放回的抽样
# 不过我对这个代码中为什么会取全量的抽样比较困惑，虽然那样选择也不是全量因为肯定是有对样本有重复的选择
# 在写类的时候最大的感受是没有感受到面对过程时需要return什么，这点我自己不是那么理的清楚，更多的是写了很多方法之类的

def bootstrap_sample(X,Y):
    N,M = X.shape
    idxs = np.random.choice(N,N,replace=True)
    return X[idxs],Y[idxs]

# 进行随机森林的算法
class RandomForest:
    def __init__(self,n_trees,max_depth,n_feats,classifier=True,criterion = "enropy")
        self.trees = []
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.n_feats = n_feats
        self.classifier = classifier
        self.criterion = criterion
        
    def fit(self,X,Y):
        self.trees = []
        for _ in range(self.n_tress):
            X_samp, Y_samp = bootstrap_sample(X,Y)
            tree = DecisionTree(
                n_feats = self.n_feats,
                max_depth=self.max_depth,
                criterion = self.criterion,
                classifier = self.classifier,
            )
            tree.fit(X_samp,Y_samp)
            self.trees.append(tree)
# 这个append的tree是append的啥 这点我自己其实有点懵
# 下面那个调用我自己也有点弄的半懂半不懂的
def predict(self,X):
    tree_peds = np.array([[t._traverse(x,t.root) for x in X] for t in self.trees])
    return self._vote(tree_preds)
# 为什么要转置，表示有点懵
def _vote(self,predictions):
    if self.classifier:
        out = [np.bincount(x).argmax() for x in predictions.T]
    else:
        out = [np.mean(x) for x in prediction.T]
    return np.array(out)



array([5, 3, 0, 4, 0, 0, 6])

In [122]:
# 代码总的来说还是比较简单的，不过对于里面的内容还是有点不是很理解透彻，主要原因是我需要再去深入的了解我写决策树的时候做的事情，需要理解类


In [123]:
# 开始对做GBDT的代码，在此之前的话需定义一些损失函数

In [92]:
import numpy as np 

class ClassProbEstimator:
    def fit(self,X,y):
        self.class_prob = y.sum() / len(y)
        
    def predict(self,X):
        pred = np.empty(X.shape[0],dtype=np.float64)
        pred.fill(self.class_prob)
        return pred
    
class MeanBaseEstimator:
    def fit(self,X,y):
        self.avg = np.mean(y)
        
    def predict(self,X):
        pred = np.empty(X.shape[0],dtype=np.float64)
        pred.fill(self.avg)
        return pred
# 加入了调用函数，将定义的类的实例也当成函数来
# 但是坦白而言没有看到作者后面利用了这个啊，比较困惑那为啥要定义这个
class MSELoss:
    def __call__(self,y,y_pred):
        return np.mean((y - y_pred)**2)
        
    def base_estimator(self):
        return MeanBaseEstimator()
# 这个是弄grad定义成这样主要是为了什么呢？这个我有点不是很理解对于我来说
# 只能说稍微有点知道了，这个计算梯度和我们如何定义损失函数关，其实不是很知道为什么会有len(y),看系数有2应该就是平方和的感觉啊
# 关于len(y)就是那个N的意思，计算的是一个样本的梯度，所以要弄一下
    def grad(self,y,y_pred):
        return -2 / len(y) * (y - y_pred)
# 线性搜索也不是那么的懂，这个h_pred是什么意思
# 这里的一个作用就是在调整步长，和作者所说的是调整weight来的有点出入
# 这里的设定更多的是输入的时候对步长进行的调整，默认其实还是按照恒定的步长
    def line_search(self,y,y_pred,h_pred):
        Lp = np.sum((y - y_pred) * h_pred)
        Lpp = np.sum(h_pred * h_pred)
        
        return 1 if np.sum(Lpp) == 0 else Lp / Lpp
# 这个eps也看不懂,是machine epsilon 可以理解为计算机在计算存储浮点数不准确，给了一个上限

class CrossEntropyLoss:
    def __call__(self,y,y_pred):
        eps = np.finfo(float).eps
        return -np.sum(y * np.log(y_pred + eps))
     
    def base_estimator(self):
        return ClassProbEstimator()
    
    def grad(self,y,y_pred):
        eps = np.finfo(float).eps
        return -y* 1/(y_pred + eps)
    
    def line_search(self,y,y_pred,h_pred):
        raise NotImplementedError
    
# 整个块为什么要这么定义我自己其实并不是很明白，为什么要这样去弄这样的结构

In [50]:
np.finfo(float).eps

2.2204460492503131e-16

In [73]:
# 定义好损失函数之后开始写GBDT的函数
# y变量的one_hot编码

import numpy as np

from .dt import DecisionTree
from .losses import MSELoss,CrossEntropyLoss

def to_one_hot(labels,n_classes=None):
    if labels.ndm > 1:
        raise ValueError("labels must have dimension 1,but got {}".format(labels.ndim))
        
    N = labels.size
    n_cols = np.max(labels) + 1 if n_classes is None else n_classes
    one_hot = np.zeros((N,n_cols))
    one_hot[np.arange(N),labels] = 1.0
    return one_hot

ModuleNotFoundError: No module named '__main__.dt'; '__main__' is not a package

In [74]:
def to_one_hot(labels,n_classes=None):
    if labels.ndim > 1:
        raise ValueError("labels must have dimension 1,but got {}".format(labels.ndim))
        
    N = labels.size
    n_cols = np.max(labels) + 1 if n_classes is None else n_classes
    one_hot = np.zeros((N,n_cols))
    one_hot[np.arange(N),labels] = 1.0
    return one_hot

In [2]:
labels = np.array([0,1,2,3,4,3,4,4,1])


In [4]:
N = labels.size
np.arange(N)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.zeros((N,n_cols))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
N=labels.size
n_cols=np.max(labels)+1
one_hot = np.zeros((N,n_cols))

In [12]:
one_hot[np.arange(N),labels] = 1.0

In [13]:
one_hot[np.arange(N),labels]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
one_hot[0,:]

array([ 1.,  0.,  0.,  0.,  0.])

In [15]:
one_hot

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [ ]:
# 先上来就定义了一大段感觉也是醉了，这样看的话确实感觉有点尴尬面向对象的语言
class GradientBoostedDecisionTree:
    def __init__(
        self,
        n_iter,
        max_depth = None,
        classifier = True,
        learning_rate = 1,
        loss = "crossentropy",
        step_size = "constant"
    ):
        self.loss = loss
        self.weights = None
        self.learners = None
        self.out_dims = None
        self.n_iter = n_iter
        self.base_estimator = None
        self.max_depth = max_depth
        self.step_size = step_size
        self.classifier = classifier
        self.learning_rate = learning_rate
        
    def fit(self,X,Y):
        if self.loss == "mse":
            loss = MSELoss()
        elif self.loss == "crossentropy":
            loss = CrossEntropyLoss()
# 后面那个为什么要那样的变换，这点我不是很懂为啥
# 这里是对Y进行的变换，如果是分类的话进行one——hot编码，如果是连续变量且纬度为1的话就变成列变量
        if self.classifier:
            Y = to_one_hot(Y.flatten())
        else:
            Y = Y.reshape(-1,1) if len(Y.shape) == 1 else Y
    
        N, M = X.shape
        self.out_dims = Y.shape[1]
        self.learners = np.empty((self.n_iter,self.out_dims),dtype=object)
        self.weights = np.ones((self.n_iter,self.out_dims))
        self.weights[1:,:] *= self.learning_rate
# 下面这些也知道是什么但是还是不懂。。。。。   
        Y_pred = np.zeros((N,self.out_dims))
        for k in range(self.out_dims):
            t = loss.base_estimator()
            t.fit(X,Y[:,k])
            Y_pred[:,k] += t,predict(X)
            self.learners[0,k] = t

        for i in range(1,self.n_iter):
            for k in range(self.out_dims):
                y,y_pred = Y[:,k],Y_pred[:,k]
                neg_grad = -1 * loss.grad(y,y_pred)

                t = DecisionTree(
                   classifier = False,max_depth=self.max_depth,criterion="mse"
                )

                t.fit(X,neg_grad)
                self.learners[i,k] = t
# 
                step = 1.0
                h_pred = t.predict(X)
                if self.step_size == "adaptive":
                    step = loss.line_search(y,y_pred,h_pred)

                self.weight[i,k] *= step
                Y_pred[:,k] += self.weight[i,k]*h_pred

        
    def predict(self,X):
        Y_pred = np.zeros((X.shape[0],self.out_dims))
        for i in range(self.n_iter):
            for k in range(self.out_dims):
                Y_pred[:,k] += self.weights[i,k] * self.learners[i,k].predict(X)
                
        if self.classifier:
            Y_pred = Y_pred.argmax(axis = 1)
            
        return Y_pred

In [136]:
y = np.array([1,0,1,0,0,1,0,0,1,0,0,0])

In [137]:
y.sum()/len(y)

0.33333333333333331

In [138]:
X = np.array([[1,2,3],[2,3,4],[3,4,4],[1,3,4],[2,3,4],[2,2,3],[2,4,1],[2,3,4],[2,3,4],[3,4,3],[1,2,3],[2,3,4]])

In [139]:
pred = np.empty(X.shape[0],dtype = np.float64)

In [140]:
pred.fill(y.sum()/len(y))

In [141]:
np.mean(y)

0.33333333333333331

In [142]:
y

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [143]:
y_pred=np.array([1,1,1,0,0,0,1,1,0,1,0,1])

In [144]:
np.mean((y - y_pred)**2)

0.58333333333333337

In [145]:
-2/len(y)*(y - y_pred)

array([-0.        ,  0.16666667, -0.        , -0.        , -0.        ,
       -0.16666667,  0.16666667,  0.16666667, -0.16666667,  0.16666667,
       -0.        ,  0.16666667])

In [146]:
N,M = X.shape

In [147]:
out_dims = Y.shape[1]

In [167]:
Y = np.array([1,0,1,0,0,1,0,0,1,0,0,0])

In [169]:
Y = to_one_hot(Y.flatten())

In [170]:
Y

array([[ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [150]:
out_dims = Y.shape[1]

In [151]:
out_dims

2

In [152]:
learners = np.empty((3,2),dtype=object)

In [153]:
weights = np.ones((3,2))

In [154]:
weights[1:,:] *= 0.1

In [155]:
Y_pred = np.zeros((N,out_dims))

In [156]:
for k in range(out_dims):
    t = CrossEntropyLoss().base_estimator()
    t.fit(X,Y[:,k])
    Y_pred[:,k] += t.predict(X)
    learners[0,k] = t
    

In [157]:
learners

array([[<__main__.ClassProbEstimator object at 0x113869278>,
       [None, None],
       [None, None]], dtype=object)

In [158]:
Y_pred

array([[ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333]])

In [161]:
for i in range(1,3):
    for k in range(2):
        y,y_pred = Y[:,k],Y_pred[:,k]
        neg_grad = -1 * CrossEntropyLoss().grad(y,y_pred)
        
        t = DecisionTree(classifier=False,max_depth=4,criterion="mse")
        t.fit(X,neg_grad)
        learners[i,k] = t

ValueError: zero-size array to reduction operation maximum which has no identity

In [179]:
neg_grad

array([ 0. ,  1.5,  0. ,  1.5,  1.5,  0. ,  1.5,  1.5,  0. ,  1.5,  1.5,
        1.5])

In [162]:
# 看GBDT最大的感受就是作者用了多维数组进行组合，这点我个人觉得还是很不错的，我之前类似的用到过，这样走一遍感觉还是很好的

In [ ]:
UP = dog()
wanzi = dog(color = 'yellow')